package tcuithemesmaker;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * Solkin Igor Viktorovich, TomClaw Software, 2003-2013
 * http://www.tomclaw.com/
 * @author Solkin
 */
public class FileChooserDialog extends javax.swing.JDialog {

  public static final int MODE_OPEN = JFileChooser.OPEN_DIALOG;
  public static final int MODE_SAVE = JFileChooser.SAVE_DIALOG;
  public static final int MODE_SCRN = JFileChooser.SAVE_DIALOG;
  public int mode;
  public File file;

  /** Creates new form FileChooserDialog */
  public FileChooserDialog( java.awt.Frame parent, boolean modal, int mode, File file ) {
    super( parent, modal );
    this.file = file;
    this.mode = mode;
    initComponents();
    if ( file != null ) {
      jFileChooser1.setSelectedFile( file );
    }
    jFileChooser1.setDialogType( mode );
    setLocationRelativeTo( null );
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFileChooser1 = new javax.swing.JFileChooser();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Выбор файла");

    jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
      if ( evt.getActionCommand().equals( "ApproveSelection" ) ) {
        if ( mode == MODE_OPEN ) {
          MainFrame.mainFrame.openTheme( jFileChooser1.getSelectedFile() );
        } else if ( mode == MODE_SAVE ) {
          MainFrame.mainFrame.saveTheme( jFileChooser1.getSelectedFile() );
        } else if ( mode == MODE_SCRN ) {
          MainFrame.mainFrame.makeScreenShot( jFileChooser1.getSelectedFile().getPath() );
        }
      }
      dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFileChooser jFileChooser1;
  // End of variables declaration//GEN-END:variables
}
